# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:  
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the tag on this image to a more stable version, using latest can result in unstable builds.
    docker:
      - image: microsoft/dotnet:latest
    steps:
      # Checkout the code as the first step.
      - checkout
      # Then simply use the dotnet container as you'd expect and run your tests
      - run:
          # Update this line with the directory that contains your tests project file
          working_directory: ./TodoApi 
          name: Restore Dependencies
          command: |
            dotnet restore
      
      - run:
           working_directory: ./TodoApi
           name: Run build
           command: dotnet build --configuration Release
        
  publish:
    docker: 
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
           working_directory: ./TodoApi
           name: Publish build
           command: |
             dotnet publish --output /publish/artifacts
      - store_artifacts:
          path: /publish/
          name: DotnetBuild
  success:
    docker:
      - image: ubuntu:latest
    steps:
    - run:
        working_directory: /publish/artifacts
        name: Print Success
        command: |
          echo "Hello your build and pulish step are comeplete" > /publish/artifacts
          echo "Successfully build"
    - store_artifacts:
        path: /publish/
        name: Success
            

workflows:
  version: 2
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  Dotnet: 
    jobs:
      - build
      - publish:
          requires:
            - build
      - success:
          filters:
             branches:
               only:
               - master
          requires:
            - build
            - publish
